version: "3.8"

services:
  backend:
    container_name: backend
    image: gobyungyong/together_back
    env_file:
      - ./.env
    ports:
      - 8000:8000

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email quddyddlrk@naver.com --agree-tos --no-eff-email -d travel-together.shop

  nginx:
    container_name: nginx
    image: gobyungyong/together_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - build_folder:/usr/share/nginx/html
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - certbot

volumes:
  build_folder:
