# Generated by Django 4.2.5 on 2023-09-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.URLField(default="naver.com"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="rhquddyd", max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
