# Generated by Django 4.2.5 on 2023-09-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_avatar_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(
                default="https://kr.object.ncloudstorage.com/travel-together/profile/basic_profile/basic.png"
            ),
        ),
    ]
