# Generated by Django 4.2.5 on 2023-09-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="subject",
            field=models.CharField(max_length=50),
        ),
    ]
