# Generated by Django 4.2.5 on 2023-09-10 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_alter_comment_board_alter_comment_writer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recomments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recomment",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="comments.comment"
            ),
        ),
        migrations.AlterField(
            model_name="recomment",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
